first commit
PhilippElizarov/go_final_project pull request #1
Opened 2024-07-08 23:04 UTC by PhilippElizarov

2024-07-09 16:39 UTC, dirtymew requested changes
Привет Филипп

хорошая работа - отлично что сделал compose 

нужно кое-что подчистить и отрефакторить код

также нужно добавить докумнентацию - описать как запускать проект как его протестировать и настроить, какие задания со * сделаны

2024-07-09 16:39 UTC, dirtymew commented on .vscode/launch.json
> +    // Use IntelliSense to learn about possible attributes.
думаю это нужно убрать и добавить в .gitignore

2024-07-09 16:39 UTC, dirtymew commented on .vscode/launch.json
> +    // Use IntelliSense to learn about possible attributes.
и еще .DS_Store

2024-07-09 16:39 UTC, dirtymew commented on Dockerfile
> +RUN go mod tidy
лучше go mod download

2024-07-09 16:39 UTC, dirtymew commented on Dockerfile
> +RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /main cmd/api/main.go cmd/api/routes.go
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 лучше в .env

2024-07-09 16:39 UTC, dirtymew commented on Dockerfile
> +FROM golang:1.21.0
используй одну версию  go в go.mod go 1.21.5

2024-07-09 16:39 UTC, dirtymew commented on .vscode/launch.json
> +    // Use IntelliSense to learn about possible attributes.
а также бинарники main.go

2024-07-09 16:39 UTC, dirtymew commented on Makefile
> +	@go build -o main cmd/api/main.go cmd/api/routes.go
а зачем?  нужно немного переделать лайут и не нужно будет так билдить ...

2024-07-09 16:39 UTC, dirtymew commented on Makefile
> +
мб тут что-то надо дописать...

2024-07-09 16:39 UTC, dirtymew commented on compose.yaml
> +      - "7540:7540"
а если порт поменятся?

2024-07-09 16:39 UTC, dirtymew commented on cmd/api/routes.go
> +package main
это стоит убрать отсюда в другой пакет

см https://github.com/golang-standards/project-layout

2024-07-09 16:39 UTC, dirtymew commented on cmd/api/routes.go
> +func handleDeleteTask(w http.ResponseWriter, r *http.Request) {
очень перегружены хендлеры - выполняют много логики

это плохо с точки зрения разработки, поддержки и тд.

нужно выдели абстрации и отрефакторить код
пусть например хендлеры отвечают только за обработку запроса его валидацию и обработку ответа

остальную логику можно вынести в другие пакеты - например все что бд работает пусть будет в database - там стоит завести структуру и заинжектить туда подлючение к бд зависимостью.... 

вот мб помогу данные материалы
https://medium.com/@shershnev/layered-architecture-implementation-in-golang-6318a72c1e10
https://github.com/golang-standards/project-layout

2024-07-09 16:39 UTC, dirtymew commented on internal/database/database.go
> +		"date" TEXT,
для date хватить и CHAR(8)

2024-07-09 16:39 UTC, dirtymew commented on internal/database/database.go
> +		"title" TEXT,
title тоже стоит ограничить по размеру

2024-07-13 12:17 UTC, PhilippElizarov commented on cmd/api/routes.go
> +package main
Удалил compose.yaml, он не нужен.

2024-07-13 12:17 UTC, PhilippElizarov commented on .vscode/launch.json
> +    // Use IntelliSense to learn about possible attributes.
Исправил

2024-07-13 12:17 UTC, PhilippElizarov commented on Dockerfile
> +RUN go mod tidy
Исправил

2024-07-13 12:23 UTC, PhilippElizarov commented on Dockerfile
> +RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /main cmd/api/main.go cmd/api/routes.go
Удалил compose.yaml.

2024-07-13 12:23 UTC, PhilippElizarov commented on Dockerfile
> +FROM golang:1.21.0
Исправил.

2024-07-13 12:26 UTC, PhilippElizarov commented on Makefile
> +
Не знаю что тут писать, удалил Makefile.

2024-07-13 12:27 UTC, PhilippElizarov commented on internal/database/database.go
> +		"date" TEXT,
Исправил.

2024-07-13 12:29 UTC, PhilippElizarov commented on internal/database/database.go
> +		"title" TEXT,
В постановке не указана длина title, поэтому не знаю на сколько ограничивать.

2024-07-13 12:32 UTC, PhilippElizarov commented on compose.yaml
> +      - "7540:7540"
Удалил compose.yaml.

2024-07-14 14:01 UTC, PhilippElizarov commented on Makefile
> +	@go build -o main cmd/api/main.go cmd/api/routes.go
Исправил. Убрал makefile.

2024-07-14 14:02 UTC, PhilippElizarov commented on cmd/api/routes.go
> +package main
Исправил.

2024-07-14 14:03 UTC, PhilippElizarov commented on cmd/api/routes.go
> +func handleDeleteTask(w http.ResponseWriter, r *http.Request) {
Исправил.

2024-07-14 16:49 UTC, closed without merging