First iteration
PhilippElizarov/go_final_project pull request #2
Opened 2024-07-14 16:50 UTC by PhilippElizarov

2024-07-15 10:13 UTC, dirtymew requested changes
Привет  Филлип

лучше все ревью в одном PR так все изменения и комментарии будут в одном месте

дал комментарии что еще поправить

2024-07-15 10:13 UTC, dirtymew commented on cmd/api/main.go
> +	if err := http.ListenAndServe(":"+port, router); err != nil {
хорошо бы добавить лог что приложение запущено на таком-то порту

2024-07-15 10:13 UTC, dirtymew commented on internal/database/database.go
> +	db, err := sql.Open("sqlite3", model.DbFile)
тут не очень хорошо - каждый раз инициализировать подключение к бд

нужно сделать один раз при старте приложения

посмотри как сделано в задании про посылки - можно завести струтуру и хранить в ней подключение и все функции сделать ее методами

еще про архитектуру - https://medium.com/@shershnev/layered-architecture-implementation-in-golang-6318a72c1e10

2024-07-15 10:13 UTC, dirtymew commented on internal/database/database.go
> +	row := db.QueryRow("SELECT * FROM scheduler WHERE id = :id", sql.Named("id", id))
лучше явно указать поля чем использовать *

2024-07-15 10:13 UTC, dirtymew commented on internal/database/database.go
> +	row := db.QueryRow("SELECT * FROM scheduler WHERE id = :id", sql.Named("id", id))
и тут это лишний запрос - хватит одного DELETE

2024-07-15 10:13 UTC, dirtymew commented on internal/database/database.go
> +	row := db.QueryRow("SELECT * FROM scheduler WHERE id = :id", sql.Named("id", id))
мб тут стоит переиспользовать метод GetTaskByID

2024-07-15 10:13 UTC, dirtymew commented on internal/database/database.go
> +	row := db.QueryRow("SELECT * FROM scheduler WHERE id = :id", sql.Named("id", id))
ну и другие методы

2024-07-15 10:13 UTC, dirtymew commented on internal/database/database.go
> +	row := db.QueryRow("SELECT id FROM scheduler WHERE id = :id", sql.Named("id", scheduler.ID))
лишний запрос

2024-07-15 10:13 UTC, dirtymew commented on internal/database/database.go
> +func PostTask(scheduler model.Scheduler) (model.Response, error) {
addTask или createTask

2024-07-15 10:13 UTC, dirtymew commented on internal/database/database.go
> +	limit := 50
лимит лучше в глобальную константу

2024-07-15 10:13 UTC, dirtymew commented on internal/database/database.go
> +func GetTask(search string) (model.Tasks, model.Response, error) {
GetTasks

2024-07-15 10:13 UTC, dirtymew commented on internal/database/database.go
> +
нужно еще ошибку из rows обработать
http://go-database-sql.org/errors.html

2024-07-15 10:13 UTC, dirtymew commented on internal/model/model.go
> +type Scheduler struct {
Task

2024-07-15 10:13 UTC, dirtymew commented on internal/model/model.go
> +const DbName string = "scheduler.db"
это лучше в main перенести

2024-07-15 10:13 UTC, dirtymew commented on internal/routes/routes.go
> +	w.Write([]byte(nextDate))
тут и везде _ , _ = w.Write(resp)

тут нужно либо явно проигнорировать ошибку или ее логировать

хорошие линтеры на это ругаться будут и не зря

2024-07-15 10:13 UTC, dirtymew commented on internal/database/database.go
> +func GetTask(search string) (model.Tasks, model.Response, error) {
есть вопрос про model.Response - я бы так не делал - мы размазываем логику и связываем компоненты

лучше просто вернуть []Task - а уже выше формировать респонс

2024-07-15 10:13 UTC, dirtymew commented on internal/model/model.go
> +type Tasks struct {
лишняя структура на мой взгляд.... просто используй []Task

2024-07-15 10:13 UTC, dirtymew commented on cmd/api/main.go
> +	appPath, err := os.Executable()
тут не очень хорошо - в разных ОС разное поведение лучше относительные пути использовать

2024-07-15 18:50 UTC, PhilippElizarov commented on internal/database/database.go
> +	row := db.QueryRow("SELECT * FROM scheduler WHERE id = :id", sql.Named("id", id))
> лучше явно указать поля чем использовать *
Исправлено

> и тут это лишний запрос - хватит одного DELETE
В этом случае тест не проходит.

2024-07-15 18:55 UTC, PhilippElizarov commented on internal/database/database.go
> +	row := db.QueryRow("SELECT id FROM scheduler WHERE id = :id", sql.Named("id", scheduler.ID))
В этом случае тест не проходит.

2024-07-15 18:57 UTC, PhilippElizarov commented on internal/model/model.go
> +const DbName string = "scheduler.db"
Перенес.

2024-07-15 19:04 UTC, PhilippElizarov commented on internal/routes/routes.go
> +	w.Write([]byte(nextDate))
Не понял зачем это, но сделал.

2024-07-15 19:21 UTC, PhilippElizarov commented on cmd/api/main.go
> +	appPath, err := os.Executable()
Этот кусок кода из Ваших же рекомендаций
Спринт 13/13: 13-14. → Тема 1/1: Спринт 13-14. Выпускной проект → Урок 2/10

Но вообще [здесь](https://pkg.go.dev/os) написано, что "Package os provides a platform-independent interface...".

Переделал на os.Getwd. Не подойдет?

2024-07-15 19:23 UTC, PhilippElizarov commented on cmd/api/main.go
> +	if err := http.ListenAndServe(":"+port, router); err != nil {
Добавил

2024-07-15 19:26 UTC, PhilippElizarov commented on internal/database/database.go
> +func PostTask(scheduler model.Scheduler) (model.Response, error) {
Исправил.

2024-07-15 19:29 UTC, PhilippElizarov commented on internal/database/database.go
> +	limit := 50
Сделал.

2024-07-15 19:30 UTC, PhilippElizarov commented on internal/database/database.go
> +func GetTask(search string) (model.Tasks, model.Response, error) {
Исправил.

2024-07-15 19:37 UTC, PhilippElizarov commented on internal/database/database.go
> +
Обработал.

2024-07-15 19:48 UTC, PhilippElizarov commented on internal/model/model.go
> +type Scheduler struct {
Переименовал.

2024-07-15 19:51 UTC, PhilippElizarov commented on internal/model/model.go
> +type Tasks struct {
Мне нравится мой вариант.

2024-07-15 20:05 UTC, PhilippElizarov commented on internal/database/database.go
> +	row := db.QueryRow("SELECT * FROM scheduler WHERE id = :id", sql.Named("id", id))
Переиспользовал.

2024-07-15 23:41 UTC, PhilippElizarov commented on internal/database/database.go
> +	db, err := sql.Open("sqlite3", model.DbFile)
Исправил.

2024-07-16 05:38 UTC, PhilippElizarov commented on internal/database/database.go
> +func GetTask(search string) (model.Tasks, model.Response, error) {
Исправил.

2024-07-16 11:24 UTC, dirtymew approved these changes
Привет Филипп

в целом неплохо получилось

задание считаю выполненным

Поздравляю и желаю удачи

2024-07-16 11:24 UTC, dirtymew commented on internal/database/database.go
> +	task, err := s.GetTaskByID(id)
уже писал что это плохо тут 2 запроса к бд можно все вделать в одном

если нужно проверить была ли строка - то можно проверить RowsAffected  и если их небыло то вернуть ошибку

тоже самое и в Update @PhilippElizarov  обрати внимание

2024-07-16 11:24 UTC, dirtymew commented on internal/model/model.go
> +type Tasks struct {
@PhilippElizarov ну это очень странный вариант - если это для того чтобы формат респонса поддержать то ок но не нужно это в сторадже делать

2024-07-16 11:24 UTC, dirtymew commented on internal/database/database.go
> +	row := db.QueryRow("SELECT * FROM scheduler WHERE id = :id", sql.Named("id", id))
не будет см другой комментарий  - подробнее описал как стоило бы сделать

2024-07-16 11:24 UTC, dirtymew commented on internal/routes/routes.go
> +	w.Write([]byte(nextDate))
потому-что ошибки нужно обрабатывать ) их игнорирования ведет к проблемам

если ты явно игнорируешь это то показываешь что это намерено сделано

2024-07-16 11:24 UTC, dirtymew commented on cmd/api/main.go
> +	appPath, err := os.Executable()
да пойдет - про os.Executable() сдано на исправление - скорее всего еще не успели поправить

2024-07-16 11:34 UTC, merged

2024-07-16 11:34 UTC, PhilippElizarov commented
@dirtymew Спасибо.